{
    "hr_policy": {
        "tools": ["pdf_retrieval_tool"],
        "triggers": ["policy", "handbook", "benefits", "hr guide", "rules"],
    },
    "change_pin": {
        "tools": ["change_pin_tool"],
        "triggers": [
            "change pin",
            "update pin",
            "new pin",
            "change my pin",
            "update my pin",
        ],
    },
    "forgot_pin": {
        "note": "B0 authentication NOT required — customer may be locked out.",
        "tools": ["forgot_pin_tool"],
        "triggers": [
            "forgot pin",
            "lost pin",
            "can't remember pin",
            "recover pin",
            "reset pin",
            "liveness",
            "nin verification",
        ],
    },
    "fund_wallet": {
        "tools": ["fund_wallet_info_tool"],
        "triggers": [
            "fund wallet",
            "top up",
            "deposit",
            "add money",
            "fund my account",
            "how to fund",
            "bank details",
        ],
    },
    "recruitment": {
        "tools": ["search_job_opportunities_tool"],
        "triggers": ["job", "vacancy", "career", "hiring", "position"],
    },
    "bills_payment": {
        "tools": [
            "pay_bill_tool",
            "get_saved_billers_tool",
            "delete_saved_biller_tool",
        ],
        "triggers": [
            "pay bill",
            "bills",
            "electricity",
            "dstv",
            "gotv",
            "startimes",
            "cable tv",
            "nepa",
            "ekedc",
            "ikedc",
            "meter",
            "smart card",
            "internet subscription",
            "betting",
            "waec",
        ],
    },
    "money_transfer": {
        "tools": [
            "transfer_money_tool",
            "get_beneficiary_name_tool",
            "get_bank_list_tool",
        ],
        "triggers": [
            "transfer",
            "send money",
            "wire",
            "pay someone",
            "bank transfer",
            "inter-bank",
            "intra-bank",
            "beneficiary",
        ],
    },
    "account_opening": {
        "note": "B0 authentication NOT required for this step.",
        "tools": ["create_customer_profile_tool"],
        "triggers": [
            "open account",
            "create account",
            "new account",
            "register",
            "sign up",
            "onboard",
            "account opening",
            "get an account",
        ],
    },
    "balance_enquiry": {
        "tools": ["balance_enquiry_tool"],
        "triggers": [
            "balance",
            "check balance",
            "account balance",
            "how much do i have",
            "wallet balance",
        ],
    },
    "forgot_password": {
        "note": "3-step flow: initiate → confirm (₦10 debit + OTP) → verify OTP → issue link. OTP expires in 10 seconds. B0 NOT required.",
        "tools": [
            "initiate_password_reset_tool",
            "confirm_password_reset_tool",
            "verify_otp_and_issue_link_tool",
        ],
        "triggers": [
            "forgot password",
            "reset password",
            "lost password",
            "can't login",
            "locked out",
            "password reset",
            "otp",
            "one time password",
            "sms code",
        ],
    },
    "general_inquiry": {
        "tools": ["web_search_tool"],
        "triggers": ["what is", "how to", "who is", "search"],
    },
    "profile_updates": {
        "tools": [
            "update_employee_profile_tool",
            "create_customer_profile_tool",
            "get_customer_details_tool",
        ],
        "triggers": ["update", "profile", "phone number", "bank account", "details"],
    },
    "airtime_purchase": {
        "tools": ["buy_airtime_tool"],
        "triggers": [
            "airtime",
            "buy airtime",
            "recharge",
            "top up phone",
            "data",
            "mtn",
            "airtel",
            "glo",
            "9mobile",
            "etisalat",
        ],
    },
    "leave_management": {
        "tools": [
            "fetch_available_leave_types_tool",
            "prepare_leave_application_tool",
            "submit_leave_application_tool",
            "fetch_leave_status_tool",
            "calculate_num_of_days_tool",
        ],
        "triggers": [
            "leave",
            "vacation",
            "sick leave",
            "day off",
            "approve",
            "leave balance",
            "resumption",
        ],
    },
    "loan_application": {
        "note": "Requires eligibility score > 70. Default tier is Bronze. Loan amount must not exceed customer loan limit. Customer must have zero outstanding loan balance.",
        "tools": ["apply_for_loan_tool"],
        "triggers": [
            "apply for loan",
            "get a loan",
            "borrow money",
            "take a loan",
            "loan application",
            "request loan",
            "need a loan",
            "how much can i borrow",
        ],
    },
    "loan_eligibility": {
        "note": "Social media URLs must pass 'validate_social_media_tool' before being passed to 'evaluate_loan_eligibility_tool'. Cached results used if < 180 days old.",
        "tools": ["validate_social_media_tool", "evaluate_loan_eligibility_tool"],
        "triggers": [
            "loan eligibility",
            "can i get a loan",
            "check eligibility",
            "credit check",
            "credit score",
            "social media check",
            "qualify for loan",
            "am i eligible",
        ],
    },
    "payslip_services": {
        "tools": ["get_payslip_tool"],
        "triggers": ["payslip", "salary", "pay statement", "earnings", "payroll"],
    },
    "travel_concierge": {
        "tools": ["search_travel_deals_tool"],
        "triggers": ["flight", "hotel", "travel", "booking", "trip"],
    },
    "data_visualization": {
        "tools": ["sql_query_tool", "generate_visualization_tool"],
        "triggers": [
            "plot",
            "chart",
            "graph",
            "visualize",
            "show as a bar chart",
            "report",
            "count",
            "average",
            "total",
            "statistics",
            "data",
        ],
    },
    "customer_authentication": {
        "note": "Must be called before any banking service request (B2–B10).",
        "tools": ["authenticate_customer_tool"],
        "triggers": [
            "login",
            "sign in",
            "access account",
            "banking services",
            "password",
            "enter password",
            "verify identity",
            "authenticate",
        ],
    },
    "social_media_validation": {
        "note": "Can also be called standalone if a customer wants to check a URL.",
        "tools": ["validate_social_media_tool"],
        "triggers": [
            "validate url",
            "check profile",
            "verify social media",
            "facebook link",
            "linkedin link",
            "instagram link",
            "twitter link",
            "tiktok link",
        ],
    },
}
